import fs from 'node:fs/promises';
import path from 'node:path';

export type GeneratedFileTarget = 'pydantic' | 'typescript';
export type GeneratedWriteAction = 'written' | 'unchanged';

const PYTHON_GENERATED_MARKER = '# Generated by SchemaBridge. Do not edit.';
const TYPESCRIPT_GENERATED_MARKER = '// Generated by SchemaBridge. Do not edit.';

export async function writeGeneratedFileIfChanged(
  filePath: string,
  content: string,
  target: GeneratedFileTarget,
): Promise<GeneratedWriteAction> {
  const normalizedContent = prepareGeneratedContent(content, target);
  const existingContent = await readTextFileIfExists(filePath);

  if (
    existingContent !== undefined &&
    normalizeGeneratedContent(existingContent) === normalizedContent
  ) {
    return 'unchanged';
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, normalizedContent, 'utf8');
  return 'written';
}

export function prepareGeneratedContent(content: string, target: GeneratedFileTarget): string {
  const marker = target === 'pydantic' ? PYTHON_GENERATED_MARKER : TYPESCRIPT_GENERATED_MARKER;
  const normalized = normalizeGeneratedContent(content);
  if (normalized.startsWith(`${marker}\n`)) {
    return normalized;
  }
  if (normalized.trim().length === 0) {
    return `${marker}\n`;
  }
  return `${marker}\n\n${normalized}`;
}

export async function readTextFileIfExists(filePath: string): Promise<string | undefined> {
  try {
    return await fs.readFile(filePath, 'utf8');
  } catch (err) {
    if (isNodeError(err) && err.code === 'ENOENT') {
      return undefined;
    }
    throw err;
  }
}

export function hasGeneratedMarker(filePath: string, content: string): boolean {
  const firstLine = normalizeGeneratedContent(content).split('\n')[0];
  if (filePath.endsWith('.py')) {
    return firstLine === PYTHON_GENERATED_MARKER;
  }
  if (filePath.endsWith('.d.ts')) {
    return firstLine === TYPESCRIPT_GENERATED_MARKER;
  }
  return false;
}

export function normalizeGeneratedContent(content: string): string {
  const lfContent = content.replaceAll('\r\n', '\n').replaceAll('\r', '\n');
  return `${stripTrailingNewlines(lfContent)}\n`;
}

function stripTrailingNewlines(content: string): string {
  let end = content.length;
  while (end > 0 && content[end - 1] === '\n') {
    end--;
  }
  return content.slice(0, end);
}

function isNodeError(error: unknown): error is Error & { code?: string } {
  return error instanceof Error && 'code' in error;
}
