import { afterEach, describe, expect, it } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { convertFolder } from '../../src/index.js';

const sourceDir = path.resolve('tests/fixtures/folder-structure');

const makeTempDir = async () => fs.mkdtemp(path.join(os.tmpdir(), 'schemabridge-folder-'));
const cleanupDirs: string[] = [];

afterEach(async () => {
  while (cleanupDirs.length > 0) {
    const dir = cleanupDirs.pop();
    if (!dir) continue;
    await fs.rm(dir, { recursive: true, force: true });
  }
});

describe('convertFolder init population', () => {
  it('populates __init__.py files for structured outputs', async () => {
    const outDir = await makeTempDir();
    cleanupDirs.push(outDir);

    await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: true,
      generateInitFiles: true,
    });

    const rootInit = await fs.readFile(path.join(outDir, '__init__.py'), 'utf8');
    expect(rootInit).toContain('from .accounts import UserAccountSchema, AddressSchema');
    expect(rootInit).toContain('from .inventory import ProductSchema');
    expect(rootInit).toContain('__all__ = ["UserAccountSchema", "AddressSchema", "ProductSchema"]');

    const accountsInit = await fs.readFile(path.join(outDir, 'accounts', '__init__.py'), 'utf8');
    expect(accountsInit).toContain('from .user_account_schema import UserAccountSchema');
    expect(accountsInit).toContain('from .nested import AddressSchema');
    expect(accountsInit).toContain('__all__ = ["UserAccountSchema", "AddressSchema"]');

    const nestedInit = await fs.readFile(
      path.join(outDir, 'accounts', 'nested', '__init__.py'),
      'utf8',
    );
    expect(nestedInit).toContain('from .address_schema import AddressSchema');
    expect(nestedInit).toContain('__all__ = ["AddressSchema"]');
  });

  it('populates __init__.py files for flat outputs', async () => {
    const outDir = await makeTempDir();
    cleanupDirs.push(outDir);

    await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
      generateInitFiles: true,
    });

    const rootInit = await fs.readFile(path.join(outDir, '__init__.py'), 'utf8');
    expect(rootInit).toContain('from .address_schema import AddressSchema');
    expect(rootInit).toContain('from .product_schema import ProductSchema');
    expect(rootInit).toContain('from .user_account_schema import UserAccountSchema');
    expect(rootInit).toContain('__all__ = ["AddressSchema", "ProductSchema", "UserAccountSchema"]');
  });
});

describe('convertFolder generated file sync', () => {
  it('writes generated files once and reports unchanged files on the next run', async () => {
    const outDir = await makeTempDir();
    cleanupDirs.push(outDir);

    const first = await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
      generateInitFiles: true,
    });

    expect(first.written).toBe(4);
    expect(first.unchanged).toBe(0);
    expect(first.deleted).toBe(0);
    expect(first.outOfDate).toBe(0);
    expect(first.errors).toEqual([]);

    const userPath = path.join(outDir, 'user_account_schema.py');
    const initPath = path.join(outDir, '__init__.py');
    const userContent = await fs.readFile(userPath, 'utf8');
    const initContent = await fs.readFile(initPath, 'utf8');
    expect(userContent.startsWith('# Generated by SchemaBridge. Do not edit.\n')).toBe(true);
    expect(initContent.startsWith('# Generated by SchemaBridge. Do not edit.\n')).toBe(true);

    const second = await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
      generateInitFiles: true,
    });

    expect(second.written).toBe(0);
    expect(second.unchanged).toBe(4);
    expect(second.deleted).toBe(0);
    expect(second.outOfDate).toBe(0);
    expect(second.errors).toEqual([]);
  });

  it('verifies out-of-date files without modifying disk', async () => {
    const outDir = await makeTempDir();
    cleanupDirs.push(outDir);

    await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
    });

    const userPath = path.join(outDir, 'user_account_schema.py');
    await fs.writeFile(userPath, '# Generated by SchemaBridge. Do not edit.\n\nBROKEN = True\n');

    const result = await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
      verify: true,
    });

    expect(result.written).toBe(0);
    expect(result.deleted).toBe(0);
    expect(result.outOfDate).toBe(1);
    expect(result.errors).toEqual([]);
    await expect(fs.readFile(userPath, 'utf8')).resolves.toContain('BROKEN = True');
  });

  it('rewrites changed generated files in normal sync and normalizes newlines', async () => {
    const outDir = await makeTempDir();
    cleanupDirs.push(outDir);

    await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
    });

    const userPath = path.join(outDir, 'user_account_schema.py');
    await fs.writeFile(
      userPath,
      '# Generated by SchemaBridge. Do not edit.\r\n\r\nBROKEN = True\r\n\r\n',
    );

    const result = await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
    });

    expect(result.written).toBe(1);
    expect(result.unchanged).toBe(2);
    expect(result.deleted).toBe(0);
    expect(result.outOfDate).toBe(0);

    const content = await fs.readFile(userPath, 'utf8');
    expect(content).not.toContain('\r');
    expect(content).toMatch(/\n$/);
    expect(content).not.toMatch(/\n\n$/);
    expect(content).not.toContain('BROKEN = True');
  });

  it('leaves stale generated files alone unless clean is enabled', async () => {
    const outDir = await makeTempDir();
    cleanupDirs.push(outDir);

    await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
    });

    const staleGeneratedPath = path.join(outDir, 'stale_schema.py');
    await fs.writeFile(
      staleGeneratedPath,
      '# Generated by SchemaBridge. Do not edit.\n\nclass StaleSchema:\n    pass\n',
    );

    const result = await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
    });

    expect(result.deleted).toBe(0);
    await expect(fs.readFile(staleGeneratedPath, 'utf8')).resolves.toContain('StaleSchema');
  });

  it('cleans only stale marked files in flat output', async () => {
    const outDir = await makeTempDir();
    cleanupDirs.push(outDir);

    await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
    });

    const handwrittenPath = path.join(outDir, 'manual.py');
    const staleGeneratedPath = path.join(outDir, 'stale_schema.py');
    const unmarkedLegacyPath = path.join(outDir, 'legacy_schema.py');
    await fs.writeFile(handwrittenPath, 'VALUE = "keep me"\n');
    await fs.writeFile(
      staleGeneratedPath,
      '# Generated by SchemaBridge. Do not edit.\n\nclass StaleSchema:\n    pass\n',
    );
    await fs.writeFile(unmarkedLegacyPath, 'class LegacySchema:\n    pass\n');

    const result = await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
      clean: true,
    });

    expect(result.deleted).toBe(1);
    await expect(fs.readFile(handwrittenPath, 'utf8')).resolves.toContain('keep me');
    await expect(fs.readFile(unmarkedLegacyPath, 'utf8')).resolves.toContain('LegacySchema');
    await expect(fs.stat(staleGeneratedPath)).rejects.toMatchObject({ code: 'ENOENT' });
  });

  it('counts stale marked files in verify clean mode without deleting them', async () => {
    const outDir = await makeTempDir();
    cleanupDirs.push(outDir);

    await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
    });

    const staleGeneratedPath = path.join(outDir, 'stale_schema.py');
    await fs.writeFile(
      staleGeneratedPath,
      '# Generated by SchemaBridge. Do not edit.\n\nclass StaleSchema:\n    pass\n',
    );

    const result = await convertFolder({
      sourceDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
      preserveStructure: false,
      clean: true,
      verify: true,
    });

    expect(result.written).toBe(0);
    expect(result.deleted).toBe(0);
    expect(result.outOfDate).toBe(1);
    await expect(fs.readFile(staleGeneratedPath, 'utf8')).resolves.toContain('StaleSchema');
  });

  it('reports conversion errors separately from warnings and does not write partial output', async () => {
    const schemaDir = await makeTempDir();
    const outDir = await makeTempDir();
    cleanupDirs.push(schemaDir, outDir);
    await fs.writeFile(
      path.join(schemaDir, 'broken.ts'),
      'export const brokenSchema = { _zod: { def: { type: "array" } } };\n',
    );

    const result = await convertFolder({
      sourceDir: schemaDir,
      outDir,
      target: 'pydantic',
      trustedInput: true,
    });

    expect(result.errors).toEqual([expect.stringContaining('Failed to convert brokenSchema')]);
    expect(result.warnings).toEqual([]);
    expect(result.written).toBe(0);
    expect(result.unchanged).toBe(0);
    expect(result.deleted).toBe(0);
    expect(result.outOfDate).toBe(0);
    await expect(fs.readdir(outDir)).resolves.toEqual([]);
  });
});
