import { describe, expect, it, afterEach } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { z } from 'zod';

import { generateFilesFromZod } from '../../src/index.js';

const schema = z.object({
  id: z.string(),
  count: z.number().int(),
});
const pythonMarker = '# Generated by SchemaBridge. Do not edit.';
const typescriptMarker = '// Generated by SchemaBridge. Do not edit.';

const makeTempDir = async () => fs.mkdtemp(path.join(os.tmpdir(), 'schemabridge-'));
const cleanupDirs: string[] = [];

afterEach(async () => {
  for (const dir of cleanupDirs) {
    await fs.rm(dir, { recursive: true, force: true });
  }
  cleanupDirs.length = 0;
});

describe('generateFilesFromZod', () => {
  it('writes pydantic file with appended extension when out has no ext', async () => {
    const tmp = await makeTempDir();
    cleanupDirs.push(tmp);
    const outBase = path.join(tmp, 'model');
    const result = await generateFilesFromZod({
      schema,
      name: 'Model',
      target: 'pydantic',
      out: outBase,
    });

    const expectedPath = `${outBase}.py`;
    expect(result).toEqual([{ path: expectedPath, target: 'pydantic', action: 'written' }]);
    const content = await fs.readFile(expectedPath, 'utf8');
    expect(content.startsWith(`${pythonMarker}\n`)).toBe(true);
    expect(content).toContain('class Model(BaseModel):');
  });

  it('writes both files to directory when target is all and reports unchanged on the next run', async () => {
    const tmp = await makeTempDir();
    cleanupDirs.push(tmp);
    const result = await generateFilesFromZod({ schema, name: 'Model', target: 'all', out: tmp });

    const pyPath = path.join(tmp, 'Model.py');
    const dtsPath = path.join(tmp, 'Model.d.ts');
    expect(result).toEqual(
      expect.arrayContaining([
        { path: pyPath, target: 'pydantic', action: 'written' },
        { path: dtsPath, target: 'typescript', action: 'written' },
      ]),
    );
    const pyContent = await fs.readFile(pyPath, 'utf8');
    const dtsContent = await fs.readFile(dtsPath, 'utf8');
    expect(pyContent.startsWith(`${pythonMarker}\n`)).toBe(true);
    expect(dtsContent.startsWith(`${typescriptMarker}\n`)).toBe(true);
    expect(pyContent).toContain('class Model(BaseModel):');
    expect(dtsContent).toContain('export interface Model');

    const second = await generateFilesFromZod({ schema, name: 'Model', target: 'all', out: tmp });
    expect(second).toEqual(
      expect.arrayContaining([
        { path: pyPath, target: 'pydantic', action: 'unchanged' },
        { path: dtsPath, target: 'typescript', action: 'unchanged' },
      ]),
    );
  });

  it('rewrites stale generated content and normalizes newlines', async () => {
    const tmp = await makeTempDir();
    cleanupDirs.push(tmp);
    const outPath = path.join(tmp, 'model.py');
    await fs.writeFile(outPath, `${pythonMarker}\r\n\r\nBROKEN = True\r\n\r\n`);

    const result = await generateFilesFromZod({
      schema,
      name: 'Model',
      target: 'pydantic',
      out: outPath,
    });

    expect(result).toEqual([{ path: outPath, target: 'pydantic', action: 'written' }]);
    const content = await fs.readFile(outPath, 'utf8');
    expect(content).not.toContain('\r');
    expect(content).not.toContain('BROKEN = True');
    expect(content).toMatch(/\n$/);
    expect(content).not.toMatch(/\n\n$/);
  });

  it('rejects when target all and out has extension', async () => {
    await expect(
      generateFilesFromZod({ schema, name: 'Model', target: 'all', out: 'model.py' }),
    ).rejects.toThrow(/must be a directory/i);
  });

  it('generates files for comprehensive schema', async () => {
    const tmp = await makeTempDir();
    cleanupDirs.push(tmp);
    const comprehensiveSchema = z.object({
      name: z.string(),
      nested: z.object({
        value: z.number(),
        deep: z.object({
          data: z.string(),
        }),
      }),
    });

    const result = await generateFilesFromZod({
      schema: comprehensiveSchema,
      name: 'Comprehensive',
      target: 'all',
      out: tmp,
    });

    expect(result.length).toBe(2);
    const pyPath = path.join(tmp, 'Comprehensive.py');
    const dtsPath = path.join(tmp, 'Comprehensive.d.ts');
    expect(result).toEqual(
      expect.arrayContaining([
        { path: pyPath, target: 'pydantic', action: 'written' },
        { path: dtsPath, target: 'typescript', action: 'written' },
      ]),
    );
    expect(await fs.readFile(pyPath, 'utf8')).toContain('class Comprehensive(BaseModel):');
    expect(await fs.readFile(dtsPath, 'utf8')).toContain('export interface Comprehensive');
  });
});
