name: 'Bug report'
description: 'Report a bug or regression in SchemaBridge'
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out as much as you can.
  - type: input
    id: summary
    attributes:
      label: 'Summary'
      description: 'Short description of the bug'
      placeholder: 'Conversion fails on nested unions'
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 'Steps to reproduce'
      description: 'Exact steps or minimal schema/command to reproduce the issue'
      placeholder: |
        1. Run `schemabridge convert zod ...`
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 'Expected behavior'
      placeholder: 'What you expected to happen'
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 'Actual behavior'
      placeholder: 'What actually happened, including error messages'
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: 'Environment'
      description: 'Please include as much as you can'
      placeholder: |
        - OS: macOS 15.0
        - Node: 20.x
        - Python: 3.11
        - SchemaBridge: 0.1.0
    validations:
      required: false
